services:
  mysql:
    image: mysql:8.0
    container_name: agricultural_info_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wine_shop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./data_init.sql:/docker-entrypoint-initdb.d/02-data_init.sql:ro
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
